---
# Developer Environment definition

local_environment:

  description: Local Environment
  test: false

  maven_mirror_url: "http://nexus-nexus.{{ openshift_host }}/nexus/content/groups/public/"
  docker_registry: 172.30.1.1:5000

  setup:
    - name: blockchain_setup    
    - name: boostcd.jaeger_setup
    - name: boostcd.couchbase_setup
    - name: boostcd.amq_setup
      templates_project: "{{ env_project }}"
    - name: boostcd.wiremock_setup  
      tag: 2.25.1
      expose: true



