---
# boost version
boost:
  version: master

# product definition
product:
  name: blockchain-demo
  description: Block Chain Demo

# Task Manager
task_manager:
  name: trello
  title: Features

# github
github:
  user: "{{ credentials.github.user }}"
  password: "{{ credentials.github.password }}"

# trello
trello:
  access_token: "{{ credentials.trello.access_token }}"
  api_key: "{{ credentials.trello.api_key }}"

jira:
  access_token: "{{ credentials.jira.access_token }}"
  username: "{{ credentials.jira.username }}"
  base_url: https://estafet.atlassian.net

couchbase:
  user: "{{ credentials.couchbase.user }}"
  password: "{{ credentials.couchbase.password }}"

webhooks:
  setup:
    - name: boostcd.github_webhook_setup

  teardown:
    - name: boostcd.github_webhook_teardown
