---
# boost version
boost:
  version: master

# product definition
product: 
  name: blockchain-demo
  description: Block Chain Demo
  repo: https://github.com/Estafet-LTD/blockchain-demo.git

# Task Manager
task_manager:
  name: trello
  title: Features