apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: node2
  name: node2
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: autonity:helloworld
    generation: null
    importPolicy: {}
    name: helloworld
status:
  dockerImageRepository: ""
