apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose --provider openshift --file docker-compose.yml --build build-config
      convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: node5
  name: node5
spec:
  ports:
  - name: "8545"
    port: 8545
    targetPort: 8545
  - name: "30353"
    port: 30353
    targetPort: 30303
  - name: 30353-udp
    port: 30353
    protocol: UDP
    targetPort: 30303
  selector:
    io.kompose.service: node5
status:
  loadBalancer: {}
