apiVersion: v1
kind: BuildConfig
metadata:
  annotations:
    kompose.cmd: kompose --provider openshift --file docker-compose.yml --build build-config
      convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: node3
  name: node3
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: node3:helloworld
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    git:
      ref: master
      uri: https://github.com/clearmatics/autonity.git
    type: Git
  strategy:
    dockerStrategy:
      dockerfilePath: ./helloworld/Dockerfile
    type: Docker
  triggers:
  - type: ConfigChange
status:
  lastVersion: 0
