apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: node-build-template
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    creationTimestamp: null
    labels:
      app: autonity
    name: node
  spec:
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: node:helloworld
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      git:
        ref: master
        uri: https://github.com/Estafet-LTD/autonity.git
      type: Git
    strategy:
      dockerStrategy:
        dockerfilePath: ./helloworld/Dockerfile
      type: Docker
    triggers:
    - type: ConfigChange
  status:
    lastVersion: 0
- apiVersion: v1
  kind: ImageStream
  metadata:
    creationTimestamp: null
    labels:
      app: autonity
    name: node
  spec:
    tags:
    - annotations: null
      from:
        kind: DockerImage
        name: autonity:helloworld
      generation: null
      importPolicy: {}
      name: helloworld
  status:
    dockerImageRepository: ""
