---
- include_role: 
    name : init

- name: Build and Deploy wiremock 
  shell: "oc new-app ethereum/client-go~https://github.com/Estafet-LTD/go-ethereum.git --strategy=docker -n {{ project }}"
  register: command_result
  failed_when: "'exists' not in command_result.stderr and command_result.rc != 0"
  changed_when: "'exists' not in command_result.stderr"
  tags:
    - openshift
    - wiremock
    
- name: Wait for the wiremock server to become available
  shell : "oc rollout status dc/wiremock-docker -n {{ project }}"
  register: command_result
  failed_when: "'exists' not in command_result.stderr and command_result.rc != 0"
  changed_when: "'exists' not in command_result.stderr"
  tags:
    - openshift
    - wiremock    
   
- name: Expose Service Wiremock
  shell: "oc expose service wiremock-docker"
  when: expose
  register: command_result
  failed_when: "'exists' not in command_result.stderr and command_result.rc != 0"
  changed_when: "'exists' not in command_result.stderr"
  tags:
    - openshift
    