---
- name: Create the {{ node }} deployment config
  shell: 'oc process -n {{ project }} -f templates/node-deploy-template.yml -p NODE={{ node }} -p NODEKEY={{ nodekey }} -p NODEPORT_85={{ nodeport85 }} -p NODEPORT_30={{ nodeport30 }} | oc apply -f -'
  register: command_result
  failed_when: "'exists' not in command_result.stderr and command_result.rc != 0"
  changed_when: "'exists' not in command_result.stderr"
  tags:
    - openshift     

- name: Wait for {{ node }} to become available
  shell : "oc rollout status dc/{{ node }}"
  register: command_result
  failed_when: "'exists' not in command_result.stderr and command_result.rc != 0"
  changed_when: "'exists' not in command_result.stderr"
  tags:
    - openshift

- name: Expose Service ({{ node }})
  shell: "oc expose service {{ node }}"
  when: expose
  register: command_result
  failed_when: "'exists' not in command_result.stderr and command_result.rc != 0"
  changed_when: "'exists' not in command_result.stderr"
  tags:
    - openshift