---
# Developer Environment definition

developer_environment:

  test: false

  maven_mirror_url: http://nexus.nexus.svc:8081/nexus/content/groups/public
  docker_registry: "{{ openshift.registry }}"

  setup:
    - name: jaeger-setup
    - name: blockchain-setup
    
    - name: couchbase-setup
      expose: true

    - name: amq-setup    
      amq_user: amq
      amq_password: amq

    - name: wiremock-setup  
      tag: 2.25.1
      expose: false
