---
# Environments definition - add new environments here

environments:

  repo: estafet-blockchain-demo

  setup:
    - name: nexus-setup    
    - name: github-webhook-setup

    - name: mq-namespace-setup
      colour: blue    
      amq_user: amq
      amq_password: amq
      templates_project: openshift

    - name: mq-namespace-setup
      colour: green    
      amq_user: amq
      amq_password: amq
      templates_project: openshift

  teardown:
    - name: github-webhook-teardown
    - name: delete-mq-namespace
      colour: blue  
    - name: delete-mq-namespace
      colour: green  

  databases:
    - name: postgresql-setup
    - name: pgadmin-setup    

  monitoring:
    - name: jaeger-setup

  stages:
    - name: build
      display: Build
      description: Build Environment
      role: edit   
      next: test
      setup:
        - name: amq-setup    
          amq_user: amq
          amq_password: amq
          templates_project: openshift
        - name: wiremock-setup  
          tag: 2.25.1
          expose: false
        - name: blockchain-setup
          service_account: true
  
    - name: test
      display: Test
      description: Test Environment
      test_repo: estafet-blockchain-demo-qa
      role: edit  
      next: perf   
      setup:
        - name: amq-setup    
          amq_user: amq
          amq_password: amq     
          templates_project: openshift 
        - name: blockchain-setup      
          service_account: true
  
    - name: perf
      display: Performance
      description: Performance Test Environment
      test_repo: estafet-blockchain-demo-qa-perf
      role: view
      next: security 
      setup:
        - name: amq-setup    
          amq_user: amq
          amq_password: amq      
          templates_project: openshift
        - name: blockchain-setup     
          service_account: true
    
    - name: security
      display: Security
      description: Security Test Environment
      test_repo: estafet-blockchain-demo-qa-security
      role: view 
      next: prod  
      setup:
        - name: amq-setup    
          amq_user: amq
          amq_password: amq      
          templates_project: openshift
        - name: blockchain-setup   
          service_account: true
                    
    - name: prod
      display: Production
      description: Production Environment
      test_repo: estafet-blockchain-demo-qa-prod
      next: end    
      setup:    
        - name: blockchain-setup   
          service_account: true
  