---
# Environments definition
environments:

  # specify the maven repository for the java image builders
  maven_mirror_url: http://nexus.nexus.svc:8081/nexus/content/groups/public
  
  # smoke tests verify the deployments to the environments (expect build)
  smoke_test_repo: estafet-blockchain-demo-smoke

  # tasks that create the platform resources that are used by all environments
  setup:
  
    # using java microservices so we need an artifact repo
    - name: nexus-setup    
    
    # webhooks allow builds or tests to automatically triggered changes to the corresponding repos are made 
    - name: github-webhook-setup

  # when a product environment is decommisioned or deleted, these are the tasks that will need to be executed
  teardown:
    - name: github-webhook-teardown

  # tasks that create resources related to monitoring - resources are created within specific monitoring namespace
  monitoring:
  
    # jaeger is an open tracing server used by the microservices 
    - name: jaeger-setup

  # stages define the discrete environments for the product - this usually starts from build to prod
  stages:
  
    # each environment is confined within a specific namespace - this one will be called "blockchain-demo-build"
    - name: build
      display: Build
      description: Build Environment   
      next: test
      # tasks to create resources for this environment
      setup:
        # a wiremock server provides stub implementations for microservices that require
        - name: wiremock-setup  
          tag: 2.25.1
          
        # creates a blockchain blockchain using the 'local' role
        - name: blockchain-setup
        
        # creates a couchbase cluster for this environment
        - name: couchbase-setup

    - name: test
      display: Test
      description: Test Environment
      test_repo: estafet-blockchain-demo-qa
      next: perf   
      setup:
        - name: amq-setup    
          amq_user: amq
          amq_password: amq     
        - name: blockchain-setup      
        - name: couchbase-setup
  
    - name: perf
      display: Performance
      description: Performance Test Environment
      test_repo: estafet-blockchain-demo-qa-perf
      next: security 
      setup:
        - name: amq-setup    
          amq_user: amq
          amq_password: amq      
        - name: blockchain-setup     
        - name: couchbase-setup        
    
    - name: security
      display: Security
      description: Security Test Environment
      test_repo: estafet-blockchain-demo-qa-security
      next: prod  
      setup:
        - name: amq-setup    
          amq_user: amq
          amq_password: amq      
        - name: blockchain-setup   
        - name: couchbase-setup        
                    
    - name: prod
      display: Production
      description: Production Environment
      test_repo: estafet-blockchain-demo-qa-prod
      next: end    
      setup:    
        # an amq broker for blue deployments
        - name: amq-setup
          application_name: blue
          amq_user: amq
          amq_password: amq 
          
        # an amq broker green deployments      
        - name: amq-setup
          application_name: green
          amq_user: amq
          amq_password: amq  
             
        - name: blockchain-setup   
        - name: couchbase-setup        
  
