---
# Environments definition - add new environments here

environments:

  repo: estafet-blockchain-demo

  roles:
    - name: couchbase-setup
      project: "{{ product }}-couchbase"

    - name: mq-namespace-setup
      colour: blue    
      amq_user: amq
      amq_password: amq
      templates_project: openshift

  teardown_roles:
    - name: delete-mq-namespace
      colour: blue  
    - name: delete-mq-namespace
      colour: green  

  stages:
    - name: build
      display: Build
      description: Build Environment
      role: edit   
      next: test
      roles:
        - name: jaeger-setup
        - name: external-postgres-setup
        - name: amq-setup    
          amq_user: amq
          amq_password: amq
          templates_project: openshift
        - name: wiremock-setup  
          tag: 2.25.1
          expose: false
      ext_roles:     
        - name: blockchain-setup
          service_account: true
  
    - name: test
      display: Test
      description: Test Environment
      test_repo: estafet-blockchain-demo-qa
      role: edit  
      next: perf   
      roles:
        - name: jaeger-setup
        - name: external-postgres-setup
        - name: amq-setup    
          amq_user: amq
          amq_password: amq     
          templates_project: openshift 
      ext_roles:     
        - name: blockchain-setup      
          service_account: true
  
    - name: perf
      display: Performance
      description: Performance Test Environment
      test_repo: estafet-blockchain-demo-qa-perf
      role: view
      next: security 
      roles:
        - name: jaeger-setup
        - name: external-postgres-setup
        - name: amq-setup    
          amq_user: amq
          amq_password: amq      
          templates_project: openshift
      ext_roles:     
        - name: blockchain-setup     
          service_account: true
    
    - name: security
      display: Security
      description: Security Test Environment
      test_repo: estafet-blockchain-demo-qa-security
      role: view 
      next: prod  
      roles:
        - name: jaeger-setup
        - name: external-postgres-setup
        - name: amq-setup    
          amq_user: amq
          amq_password: amq      
          templates_project: openshift
      ext_roles:     
        - name: blockchain-setup   
          service_account: true
                    
    - name: prod
      display: Production
      description: Production Environment
      test_repo: estafet-blockchain-demo-qa-prod
      next: end    
      roles:
        - name: jaeger-setup
        - name: external-postgres-setup        
      ext_roles:     
        - name: blockchain-setup   
          service_account: true
  