---
# Environments definition - add new environments here

environments:

  jaeger: true
  db: postgres
  amq: true
  
  ext_roles:     
    - name: blockchain-setup
  
  stages:
    - name: build
      display: Build
      description: Build Environment
      role: edit   
      wiremock: true 
      next: test
       
    - name: test
      display: Test
      description: Test Environment
      test_repo: estafet-blockchain-demo-qa
      role: edit  
      wiremock: false  
      next: sit   
        
    - name: sit
      display: SIT
      description: SIT Environment
      test_repo: estafet-blockchain-demo-qa
      role: view
      wiremock: false     
      next: uat
  
    - name: uat
      display: UAT
      description: UAT Environment
      role: view
      wiremock: false   
      next: perf
  
    - name: perf
      display: Performance
      description: Performance Test Environment
      test_repo: estafet-blockchain-demo-qa
      role: view
      wiremock: false 
      next: security 
  
    - name: security
      display: Security
      description: Security Test Environment
      test_repo: estafet-blockchain-demo-qa
      role: view 
      wiremock: false 
      next: prod  
            
    - name: prod
      display: Production
      description: Production Environment
      test_repo: estafet-blockchain-demo-qa-prod
      wiremock: false
      next: end        