---
# Environments definition
environments:

  maven_mirror_url: http://nexus.nexus.svc:8081/nexus/content/groups/public
  smoke_test_repo: estafet-blockchain-demo-qa-smoke-test

  setup:
    - name: nexus-setup     
    - name: github-webhook-setup

  teardown:
    - name: github-webhook-teardown

  monitoring:
    - name: jaeger-setup

  stages:
    - name: build
      display: Build
      description: Build Environment   
      next: test
      setup:
        - name: wiremock-setup  
          tag: 2.25.1
        - name: blockchain-setup
        - name: couchbase-setup

    - name: test
      display: Test
      description: Test Environment
      test_repo: estafet-blockchain-demo-qa
      next: perf   
      setup:
        - name: amq-setup      
        - name: blockchain-setup      
        - name: couchbase-setup
  
    - name: perf
      display: Performance
      description: Performance Test Environment
      test_repo: estafet-blockchain-demo-qa-perf
      next: security 
      setup:
        - name: amq-setup      
        - name: blockchain-setup     
        - name: couchbase-setup        
    
    - name: security
      display: Security
      description: Security Test Environment
      test_repo: estafet-blockchain-demo-qa-security
      next: prod  
      setup:
        - name: amq-setup    
        - name: blockchain-setup   
        - name: couchbase-setup        
                    
    - name: prod
      display: Production
      description: Production Environment
      test_repo: estafet-blockchain-demo-qa-prod
      next: end    
      setup:    
        - name: amq-setup
          application_name: blue  
        - name: amq-setup
          application_name: green
        - name: blockchain-setup   
        - name: couchbase-setup        
  
