---
# boost version
boost:
  version: master

# product definition
product: 
  name: blockchain-demo
  description: Block Chain Demo
  repo: estafet-blockchain-demo

# Task Manager
task_manager:
  name: trello
  title: Features

# trello
trello:
  access_token: "{{ secrets.trello.access_token }}"
  api_key: "{{ secrets.trello.api_key }}"

# jira
jira:
  access_token: "{{ secrets.jira.access_token }}"
  username: "{{ secrets.jira.username }}"
  base_url: https://estafet.atlassian.net

# github
github:
  org: Estafet-LTD
  user: "{{ secrets.github.user }}"
  password: "{{ secrets.github.password }}"

# couchbase
couchbase:
  user: "{{ secrets.couchbase.user }}"
  password: "{{ secrets.couchbase.password }}"