---
# boost version
boost:
  version: 0.2.0

# product definition
product: 
  name: blockchain-demo
  description: Block Chain Demo
  repo: estafet-blockchain-demo

# Task Manager
task_manager:
  name: trello
  title: Features